Small tweaks

diff --git a/files/utils/bin/gpgwot b/files/utils/bin/gpgwot
--- a/files/utils/bin/gpgwot
+++ b/files/utils/bin/gpgwot
@@ -1,10 +1,24 @@
 #!/bin/bash
 
+set -ie
+
 FMT=svg
 LAYOUT=dot
 
 KEYRING=${1:-~/.gnupg/pubring.gpg}
 
+checkcommand() {
+	cmd="${1}"
+	command -v "${cmd}" >/dev/null 2>&1 || {
+		echo >&2 "Required executable '${cmd}' not found";
+		exit 1;
+	}
+}
+
+checkcommand gpg
+checkcommand sig2dot
+checkcommand dot
+checkcommand eog
 gpg --list-sigs --keyring ${KEYRING} | sig2dot -q | \
 	dot -T${FMT} -K${LAYOUT} -Gconcentrate=true > ~/.gnupg/pubring.${FMT}
 eog ~/.gnupg/pubring.${FMT}
